name: Docker Images CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Build the Docker image for the backend
            run: docker build . --file backend/Dockerfile --tag my-image-name-backend:$(date +%s)
        - name: Build the Docker image for the frontend
            run: docker build . --file frontend/Dockerfile --tag my-image-name-frontend:$(date +%s)
